before:
  hooks:
    - go mod download
builds:
  - id: release
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    main: ./main.go
    binary: charts-syncer
dockers:
  dockerfile: Dockerfile
  binaries:
    - charts-syncer
  images_templates:
    - "gcr.io/bitnami-images/charts-syncer:{{ .Version }}"
    - "gcr.io/bitnami-images/charts-syncer:lastest"
  build_flag_templates:
  - "--build-arg"
  - "IMAGE_VERSION={{ .Version }}"
  skip_push: true
archives:
  - replacements:
      386: i386
      amd64: x86_64
    name_template: "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
    files:
      - README.md
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
