apiVersion: v1
kind: ConfigMap
metadata:
  name: charts-syncer-config
data:
  charts-syncer.yaml: |-
    #
    # Example config file
    #
    source:
      repo:
        kind: "HELM"
        url: "http://localhost:8080" # local test source repo
        # auth:
        #   username: "USERNAME"
        #   password: "PASSWORD"
    target:
      containerRegistry: "k8s.container.registry.io"
      containerRepository: "repository/demo/k8s"
      repo:
        kind: "CHARTMUSEUM"
        url: "http://localhost:9090" # local test target repo
        # auth:
        #   username: "USERNAME"
        #   password: "PASSWORD"